### PR TITLE
0.10.0 wipes docker credentials upon app update

### LINKED ISSUE #220: 0.10.0 wipes docker credentials upon app update
*Version* 0.10.0
*Pre-requisite* A private docker image created on CF using this v0.10.0 plugin. The private docker repo url along with credentials are provided to CF.
*Problem* When updating a docker application using bluegreen stragey, the credentials are completely removed, then fails to retrieve the docker image.

My suspicion is that the the copy_bits operation is wiping out all the specified credentials. Perhaps CopyApp should be skipped for docker applications.

### PR DESCRIPTION
**Pull request by sleungcy**
#220 
Skip copy_bits if a docker image is specified

### CODE REVIEW

**Comment by janosbinder** [comment]
LGTM

@ArthurHlt what is your take on this?

**Comment by janosbinder** [comment]
@sleungcy please do a `go fmt` and commit again, and I will merge it. Thanks for the contribution!

**Comment by ScottGuymer** [comment]
@janosbinder @ArthurHlt 

how often is it expected to publish a new release containing fixes like this?

**Comment by janosbinder** [comment]
We are having a bit capacity problem on the development and releases. @ArthurHlt @gberche-orange what is your take on this? How often do we plan a release? Bi-monthly maybe?

**Comment by ArthurHlt** [comment]
@janosbinder I agree with you, for now I was just waiting more new features/bug fixes before releasing without deadline but this was not the best approach.

**Comment by ScottGuymer** [comment]
Is it not possible to automate releases as new things are fixed? Having to wait 2 weeks to get a bug fix that is blocking is a bit painful.

**Comment by janosbinder** [comment]
Well we no longer have an acceptance environment, where we can execute the tests against a small CF landscape. Therefore this has to be solved, before any automated release process is put in place.

**Pull request merged**
