### PR TITLE
allow to specify service binding params as raw json string

### PR DESCRIPTION
**Pull request by abendt**
this PR adds an extra parameter to the _cloudfoundry_app_. It allows to specify service binding params as raw json string.

https://github.com/mevansam/terraform-provider-cf/issues/199

### CODE REVIEW

**Comment by janosbinder** [comment]
Thank you Alfonso - once you have addressed the comments of @gberche-orange I will review it and rebase it on this repo so we can run the tests.

**Comment by abendt** [comment]
@gberche-orange

regarding your request to add an acceptance test

i was finally able to get to a working acceptance test setup and was able to run one of the tests:
`TF_ACC=1 go test -v -run TestAccApp_app1`

first i tried some arbitrary parameters in  _params_ and _params_json_. This does not seem to work as CF seems to validate the params: `Service broker error: the configuration parameter 'foo' is not a valid option`

Next i tried to find a "real" parameter. As i was using the p.mysql service i checked the doc: https://docs.pivotal.io/p-mysql/2-2/change-default.html#parameters
However the _workload_ parameter i tried also does not work (same error message `workload is not a valid option`).

It looks like the PCFDev DB does not support custom params.
Also the definition of such params in the acceptance tests would tie the testsuite against one particular CF environment (the Tests need to reference a specific service that supports the params).

Would it be acceptable for you to accept the PR w/o adding acceptance tests?
Do you see other options?

**Comment by abendt** [comment]
> Can you please check whether the targeted service broker is indeed serving to the following ?

prohably not. i was trying to run a single test only: `TF_ACC=1 go test -v -run TestAccApp_app1`. This tests requires some additional environment variables: `TEST_SERVICE_1`, `TEST_SERVICE_2`and `TEST_SERVICE_PLAN`. when they are not set, the test fails: https://github.com/mevansam/terraform-provider-cf/blob/dev/cloudfoundry/provider_test.go#L234

I assumed i could set them to some available marketplace service: `export TEST_SERVICE_1=p.mysql`. Prohably that assumption is wrong?

Are there dependencies between the Acceptance Tests? I assumed i could run only a single one, but your comment makes me wonder if that is not the case.

**Comment by janosbinder** [comment]
It seems the tests run through against our acceptance environment. Details are at https://github.com/mevansam/terraform-provider-cf/pull/202

**Comment by gberche-orange** [comment]
@abendt 

> Are there dependencies between the Acceptance Tests? I assumed i could run only a single one, but your comment makes me wonder if that is not the case.

I'm not sure, the cf cats service broker is *at least* installed in this test, it might also be installed elsewhere as a result of #186 and potentially the `TEST_SERVICE_1`env var is interferring

https://github.com/cloudfoundry-community/terraform-provider-cf/blob/de9c8d3ee0ecc5bfa28fb00e4b2aea6ee5b84770/cloudfoundry/resource_cf_service_instance_test.go#L81-L108

**Comment by ArthurHlt** [comment]
Take care that your PR has been added to PR #203. You  probably want to test it take care that you need terraform 0.12 for using this.
When I wrote this lines, state migration to handle changes is not yet made. Prefers test without previous tfstate.

I'm closing it to focus on #203 but thanks for the PR.

**Comment by innokenty** [comment]
Hey @abendt ! We stopped using your custom branch here at MHP, you can now safely delete it!  🎉

**Pull request closed without merging**
